services:
  netbootxyz:
    container_name: netbootxyz
    environment:
      #- MENU_VERSION=2.0.84
      - WEB_APP_PORT=3000
    networks:
      - netboot_proxy
    ports:
      #- "3000:3000"
      - "69:69/udp"
      #- "8080:80"
    volumes:
      - ./config:/config
      - ./assets:/assets
    restart: unless-stopped
    image: ghcr.io/netbootxyz/netbootxyz
    # image: linuxserver/netbootxyz:0.7.6
  proxy-dhcp:
    container_name: proxy-dhcp
    build:
      network: host
      context: dnsmasq
    networks:
      physical_network:  # MACVLAN
        ipv4_address: 192.168.1.200
    cap_add:
      - NET_ADMIN
    environment:
      - subnet=192.168.1.0
      - subnet_mask=255.255.255.0
      - bios_file=hardware-native
      - uefi_file=hardware-native
      - pxe_server_ip=192.168.1.50

networks:
  netboot_proxy:
    external: true
  physical_network:
    external: true
